{{- if and .Values.executionAgent.enabled .Values.executionAgent.worker.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "port-ocean.executionAgent.serviceName" . }}
  labels:
    {{- include "port-ocean.executionAgent.labels" $ | nindent 4 }}
  annotations:
    {{- if .Values.executionAgent.service.annotations }}
      {{- toYaml .Values.executionAgent.service.annotations | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.executionAgent.service.type }}
  ports:
    - name: ocean-port
      protocol: TCP
      port: {{ .Values.executionAgent.service.port }} 
      targetPort: {{ .Values.executionAgent.service.port }}
  selector:
    app: {{ include "port-ocean.executionAgent.deploymentName" . }}
{{- end }}